"$schema" = "https://starship.rs/config-schema.json"

format = """
[](color_orange)\
$os\
[](bg:color_yellow fg:color_orange)\
$directory\
[](bg:color_aqua fg:color_yellow)\
$git_branch\
$git_status\
[](bg:color_blue fg:color_aqua)\
$azure\
[](bg:color_bg3 fg:color_blue)\
[](bg:color_bg1 fg:color_bg3)\
[ ](fg:color_bg1)\
$line_break\
[╰─](fg:color_bg1)$character
"""

add_newline = true

## Palettes
palette = "gruvbox_dark"

[palettes.gruvbox_dark]
color_fg0 = "#fbf1c7"
color_bg1 = "#3c3836"
color_bg3 = "#665c54"
color_blue = "#458588"
color_aqua = "#689d6a"
color_green = "#98971a"
color_orange = "#d65d0e"
color_purple = "#b16286"
color_red = "#cc241d"
color_yellow = "#d79921"

## Modules
[azure]
disabled = false
format = "[[ $symbol($subscription)](bg:color_blue fg:color_fg0)]($style)"
symbol = "󰠅 "
style = "bg:color_blue"

[character]
disabled = false
success_symbol = "[󰍟](fg:yellow)"
error_symbol = "[󰍟](fg:red)"


[directory]
format = "[ $path ]($style)"
style = "bg:color_yellow fg:color_fg0"
truncation_length = 2 
truncation_symbol = "…/"
truncate_to_repo = true

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = "[[ $symbol $branch ](bg:color_aqua fg:color_fg0)]($style)"

[git_status]
style = "bg:color_aqua"
format = "[[($all_status$ahead_behind )](bg:color_aqua fg:color_fg0)]($style)"

[line_break]
disabled = false

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"
format = "[$symbol ]($style)"

[os.symbols]
Alpine = ""
Arch = "󰣇"
CentOS = ""
Debian = "󰣚"
Fedora = "󰣛"
Gentoo = "󰣨"
Linux = "󰌽"
Macos = "󰀵"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
SUSE = ""
Ubuntu = "󰕈"
Windows = "󰍲"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = "[ $user ]($style)"

